DATA_FOLDER = "data"
DB_VERSION = "0.5"
EVENT_GET = 0
EVENT_MODEL_1_BETTER = 1
EVENT_MODEL_2_BETTER = 2
EVENT_BOTH_GOOD = 3
EVENT_BOTH_BAD = 4
EVENT_SKIP = 5
EVENT_COMMENT_BAD_PROMPT = 6
EVENT_COMMENT_OTHER = 7

SBS_TYPE_SINGLE = "single"
SBS_TYPE_DOUBLE = "sbs"

ACTION_EVENTS = [
    EVENT_MODEL_1_BETTER,
    EVENT_MODEL_2_BETTER,
    EVENT_BOTH_GOOD,
    EVENT_BOTH_BAD,
]

COMMENT_EVENTS = [EVENT_COMMENT_BAD_PROMPT, EVENT_COMMENT_OTHER]
